services:
  app: 
    image: ghcr.io/muhammadfahrul09/tele-bot:main
    restart: always
    volumes:
      - "./db:/app/prisma/db"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - USER_BOT_TOKEN=${USER_BOT_TOKEN}
      - ADMIN_BOT_TOKEN=${ADMIN_BOT_TOKEN}
      - DEBUG=${DEBUG}